### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by iEmaz** [ABSphreak/ABSphreak#9] opened 2023-05-11 22:41 UTC
Hello, I was curious on how you made that welcome gif at the top of the readme, can you tell me how?

**Comment by Arindam-7** [comment] 2023-05-30 18:25
You can create on for yourself using [this site](https://msgif.net/)

**Comment by Arindam-7** [comment] 2023-05-30 18:25
> Hello, I was curious on how you made that welcome gif at the top of the readme, can you tell me how?

You can create one for yourself using [this site](https://msgif.net/).

**Comment by ABSphreak** [comment] 2023-09-18 06:52
Duplicate of https://github.com/ABSphreak/ABSphreak/issues/4.
Please refer to Issue https://github.com/ABSphreak/ABSphreak/issues/4.
Thanks :)

**Closed as completed by ABSphreak** 2023-09-18 06:52 UTC
