### ISSUE TITLE
About GIF

### ISSUE THREAD

**Issue by tonngw** [ABSphreak/ABSphreak#8] opened 2022-07-09 09:08 UTC
I want to know the "Welcome to ABSphreak's GitHub" GIF, it is how to generate quickly. Is there a website for that?

**Comment by ABSphreak** [comment] 2022-07-09 09:57
Duplicate of https://github.com/ABSphreak/ABSphreak/issues/4.
Please refer to Issue https://github.com/ABSphreak/ABSphreak/issues/4.

**Closed as completed by ABSphreak** 2022-07-09 09:57 UTC
Labels: AMA

**Comment by tonngw** [comment] 2022-07-10 01:04
OK, thank you
